// data-katalog.js
// EDIT BAGIAN INI UNTUK MENGUBAH ATAU MENAMBAH PRODUK KATALOG
const catalogData = [
    {
        id: 'sv-l2-001', category: 'lipat2',
        imageSrc: 'https://raw.githubusercontent.com/sakinavisuals/sakinavisuals.github.io/fb88133df7cdebdabd9a91a8b0fff6fedaa1022e/images/cat_lipat2/SV-LP2-001.jpg', 
        altText: 'Undangan Softcover Lipat 2 Klasik', 
        codeCard: 'KODE : SV-L2-001', 
        detailsCard: ['Art Carton 260gsm', 'A4 Dilipat', 'Floral Elegan'],
        titlePopup: 'UNDANGAN SOFTCOVER LIPAT 2', 
        codePopup: 'SV-L2-001', 
        bahanPopup: 'Bahan Aster 200 Gsm',
        ukuranPopup: 'Uk. Tertutup 19 X 12,8 cm | Uk. Terbuka 19 X 25,6 cm',
        bonusPopup: ['Plastik OPP Bening (Sesuai Jumlah Undangan)', 'Label Nama (Free Print Out Nama Tamu)', 'Packing Kardus agar paket aman di pengiriman'],
        catatanTambahanPopup: '- Bisa request tambahan: Thank You Card, Kartu Souvenir, Denah Lokasi (Silahkan chat admin untuk info & biaya tambahan).',
        hargaTiersPopup: [ { jumlah: "300 pcs", harga: "Rp. 2.200" }, { jumlah: "500 pcs", harga: "Rp. 1.700" }, { jumlah: "1000 pcs", harga: "Rp. 1.200" } ],
        estimasiPengerjaanPopup: '7-10 Hari Kerja (setelah Desain FIX & DP diterima)',
        pengirimanDariPopup: 'Dari Kota Surakarta (Solo), Jawa Tengah',
        jasaKirimPopup: 'JNE, J&T, POS Indonesia, Wahana, SiCepat, Kargo (untuk partai besar), atau sesuai permintaan.',
        notePengirimanPopup: 'Bisa juga diambil langsung ke lokasi kami (dengan perjanjian).'
    },
    {
        id: 'sv-l2-002', category: 'lipat2',
        imageSrc: 'https://raw.githubusercontent.com/sakinavisuals/sakinavisuals.github.io/fb88133df7cdebdabd9a91a8b0fff6fedaa1022e/images/cat_lipat2/SV-LP2-002.jpg', 
        altText: 'Undangan Lipat 2 Modern', codeCard: 'KODE : SV-L2-002',
        detailsCard: ['Jasmin White 200gsm', 'A4 Dilipat', 'Modern Minimalis'],
        titlePopup: 'UNDANGAN LIPAT 2 MODERN MINIMALIS', codePopup: 'SV-L2-002',
        bahanPopup: 'Kertas Jasmin White Import 200 Gsm', ukuranPopup: 'Uk. Tertutup 15 X 15 cm (Bisa Custom)',
        bonusPopup: ['Plastik OPP Eksklusif', 'Label Nama Tamu (Kosong)', 'Packing Bubble Wrap per 100pcs'],
        catatanTambahanPopup: 'Desain bisa disesuaikan dengan preferensi warna Anda. Tersedia opsi upgrade ke hotprint/emboss (Chat Admin untuk detail).',
        hargaTiersPopup: [ { jumlah: "300 pcs", harga: "Rp. 2.500" }, { jumlah: "500 pcs", harga: "Rp. 2.000" }, { jumlah: "1000 pcs", harga: "Rp. 1.500" } ],
        estimasiPengerjaanPopup: '7-12 Hari Kerja', pengirimanDariPopup: 'Dari Kota Surakarta (Solo)',
        jasaKirimPopup: 'Semua ekspedisi besar, GoSend/GrabExpress (area Solo)',
        notePengirimanPopup: 'Free konsultasi desain sampai fix.'
    },
    {
        id: 'sv-l2-003', category: 'lipat2',
        imageSrc: 'https://raw.githubusercontent.com/sakinavisuals/sakinavisuals.github.io/fb88133df7cdebdabd9a91a8b0fff6fedaa1022e/images/cat_lipat2/SV-LP2-001.jpg', 
        altText: 'Undangan Softcover Lipat 2 Klasik', 
        codeCard: 'KODE : SV-L2-003', 
        detailsCard: ['Art Carton 260gsm', 'A4 Dilipat', 'Floral Elegan'],
        titlePopup: 'UNDANGAN SOFTCOVER LIPAT 2', 
        codePopup: 'SV-L2-003', 
        bahanPopup: 'Bahan Aster 200 Gsm',
        ukuranPopup: 'Uk. Tertutup 19 X 12,8 cm | Uk. Terbuka 19 X 25,6 cm',
        bonusPopup: ['Plastik OPP Bening (Sesuai Jumlah Undangan)', 'Label Nama (Free Print Out Nama Tamu)', 'Packing Kardus agar paket aman di pengiriman'],
        catatanTambahanPopup: '- Bisa request tambahan: Thank You Card, Kartu Souvenir, Denah Lokasi (Silahkan chat admin untuk info & biaya tambahan).',
        hargaTiersPopup: [ { jumlah: "300 pcs", harga: "Rp. 2.200" }, { jumlah: "500 pcs", harga: "Rp. 1.700" }, { jumlah: "1000 pcs", harga: "Rp. 1.200" } ],
        estimasiPengerjaanPopup: '7-10 Hari Kerja (setelah Desain FIX & DP diterima)',
        pengirimanDariPopup: 'Dari Kota Surakarta (Solo), Jawa Tengah',
        jasaKirimPopup: 'JNE, J&T, POS Indonesia, Wahana, SiCepat, Kargo (untuk partai besar), atau sesuai permintaan.',
        notePengirimanPopup: 'Bisa juga diambil langsung ke lokasi kami (dengan perjanjian).'
    },
    {
        id: 'sv-l2-004', category: 'lipat2',
        imageSrc: 'https://raw.githubusercontent.com/sakinavisuals/sakinavisuals.github.io/fb88133df7cdebdabd9a91a8b0fff6fedaa1022e/images/cat_lipat2/SV-LP2-002.jpg', 
        altText: 'Undangan Lipat 2 Modern', codeCard: 'KODE : SV-L2-004',
        detailsCard: ['Jasmin White 200gsm', 'A4 Dilipat', 'Modern Minimalis'],
        titlePopup: 'UNDANGAN LIPAT 2 MODERN MINIMALIS', codePopup: 'SV-L2-004',
        bahanPopup: 'Kertas Jasmin White Import 200 Gsm', ukuranPopup: 'Uk. Tertutup 15 X 15 cm (Bisa Custom)',
        bonusPopup: ['Plastik OPP Eksklusif', 'Label Nama Tamu (Kosong)', 'Packing Bubble Wrap per 100pcs'],
        catatanTambahanPopup: 'Desain bisa disesuaikan dengan preferensi warna Anda. Tersedia opsi upgrade ke hotprint/emboss (Chat Admin untuk detail).',
        hargaTiersPopup: [ { jumlah: "300 pcs", harga: "Rp. 2.500" }, { jumlah: "500 pcs", harga: "Rp. 2.000" }, { jumlah: "1000 pcs", harga: "Rp. 1.500" } ],
        estimasiPengerjaanPopup: '7-12 Hari Kerja', pengirimanDariPopup: 'Dari Kota Surakarta (Solo)',
        jasaKirimPopup: 'Semua ekspedisi besar, GoSend/GrabExpress (area Solo)',
        notePengirimanPopup: 'Free konsultasi desain sampai fix.'
    },
    {
        id: 'sv-l3-001', category: 'lipat3',
        imageSrc: 'https://raw.githubusercontent.com/sakinavisuals/sakinavisuals.github.io/refs/heads/main/images/cat_amplop/SV-AMP-001.webp', 
        altText: 'Undangan Lipat 3 Rustic', codeCard: 'KODE : SV-L3-001',
        detailsCard: ['Ivory 230gsm + Doff', 'A4 Lipat Tiga', 'Rustic Vintage'],
        titlePopup: 'UNDANGAN LIPAT 3 RUSTIC VINTAGE', codePopup: 'SV-L3-001',
        bahanPopup: 'Kertas Ivory 230 Gsm + Laminasi Doff', ukuranPopup: 'Uk. Terbuka 21 X 29.7 cm, Uk. Jadi (dilipat) +/- 21 X 10 cm',
        bonusPopup: ['Plastik OPP', 'Label Nama (Free Print)', 'Denah Lokasi Sederhana (Free)'],
        catatanTambahanPopup: 'Cocok untuk informasi yang lebih banyak. Bisa request tambahan foto prewedding (Chat Admin).',
        hargaTiersPopup: [ { jumlah: "300 pcs", harga: "Rp. 2.800" }, { jumlah: "500 pcs", harga: "Rp. 2.300" }, { jumlah: "1000 pcs", harga: "Rp. 1.800" } ],
        estimasiPengerjaanPopup: '10-14 Hari Kerja', pengirimanDariPopup: 'Dari Kota Surakarta (Solo)',
        jasaKirimPopup: 'Pos Indonesia, JNE, J&T, atau kargo pilihan',
        notePengirimanPopup: 'Desain dapat disesuaikan dengan tema pernikahan Anda.'
    },
    {
        id: 'sv-l3-002', category: 'lipat3',
        imageSrc: 'https://raw.githubusercontent.com/sakinavisuals/sakinavisuals.github.io/refs/heads/main/images/cat_lipat3/SV-LP3-002.webp', 
        altText: 'Undangan Lipat 3 Rustic', codeCard: 'KODE : SV-L3-002',
        detailsCard: ['Ivory 230gsm + Doff', 'A4 Lipat Tiga', 'Rustic Vintage'],
        titlePopup: 'UNDANGAN LIPAT 3 RUSTIC VINTAGE', codePopup: 'SV-L3-002',
        bahanPopup: 'Kertas Ivory 230 Gsm + Laminasi Doff', ukuranPopup: 'Uk. Terbuka 21 X 29.7 cm, Uk. Jadi (dilipat) +/- 21 X 10 cm',
        bonusPopup: ['Plastik OPP', 'Label Nama (Free Print)', 'Denah Lokasi Sederhana (Free)'],
        catatanTambahanPopup: 'Cocok untuk informasi yang lebih banyak. Bisa request tambahan foto prewedding (Chat Admin).',
        hargaTiersPopup: [ { jumlah: "300 pcs", harga: "Rp. 2.800" }, { jumlah: "500 pcs", harga: "Rp. 2.300" }, { jumlah: "1000 pcs", harga: "Rp. 1.800" } ],
        estimasiPengerjaanPopup: '10-14 Hari Kerja', pengirimanDariPopup: 'Dari Kota Surakarta (Solo)',
        jasaKirimPopup: 'Pos Indonesia, JNE, J&T, atau kargo pilihan',
        notePengirimanPopup: 'Desain dapat disesuaikan dengan tema pernikahan Anda.'
    },
    {
        id: 'sv-l3-003', category: 'lipat3',
        imageSrc: 'https://raw.githubusercontent.com/sakinavisuals/sakinavisuals.github.io/refs/heads/main/images/cat_amplop/SV-AMP-001.webp', 
        altText: 'Undangan Lipat 3 Rustic', codeCard: 'KODE : SV-L3-003',
        detailsCard: ['Ivory 230gsm + Doff', 'A4 Lipat Tiga', 'Rustic Vintage'],
        titlePopup: 'UNDANGAN LIPAT 3 RUSTIC VINTAGE', codePopup: 'SV-L3-003',
        bahanPopup: 'Kertas Ivory 230 Gsm + Laminasi Doff', ukuranPopup: 'Uk. Terbuka 21 X 29.7 cm, Uk. Jadi (dilipat) +/- 21 X 10 cm',
        bonusPopup: ['Plastik OPP', 'Label Nama (Free Print)', 'Denah Lokasi Sederhana (Free)'],
        catatanTambahanPopup: 'Cocok untuk informasi yang lebih banyak. Bisa request tambahan foto prewedding (Chat Admin).',
        hargaTiersPopup: [ { jumlah: "300 pcs", harga: "Rp. 2.800" }, { jumlah: "500 pcs", harga: "Rp. 2.300" }, { jumlah: "1000 pcs", harga: "Rp. 1.800" } ],
        estimasiPengerjaanPopup: '10-14 Hari Kerja', pengirimanDariPopup: 'Dari Kota Surakarta (Solo)',
        jasaKirimPopup: 'Pos Indonesia, JNE, J&T, atau kargo pilihan',
        notePengirimanPopup: 'Desain dapat disesuaikan dengan tema pernikahan Anda.'
    },
    {
        id: 'sv-l3-004', category: 'lipat3',
        imageSrc: 'https://raw.githubusercontent.com/sakinavisuals/sakinavisuals.github.io/refs/heads/main/images/cat_lipat3/SV-LP3-002.webp', 
        altText: 'Undangan Lipat 3 Rustic', codeCard: 'KODE : SV-L3-004',
        detailsCard: ['Ivory 230gsm + Doff', 'A4 Lipat Tiga', 'Rustic Vintage'],
        titlePopup: 'UNDANGAN LIPAT 3 RUSTIC VINTAGE', codePopup: 'SV-L3-004',
        bahanPopup: 'Kertas Ivory 230 Gsm + Laminasi Doff', ukuranPopup: 'Uk. Terbuka 21 X 29.7 cm, Uk. Jadi (dilipat) +/- 21 X 10 cm',
        bonusPopup: ['Plastik OPP', 'Label Nama (Free Print)', 'Denah Lokasi Sederhana (Free)'],
        catatanTambahanPopup: 'Cocok untuk informasi yang lebih banyak. Bisa request tambahan foto prewedding (Chat Admin).',
        hargaTiersPopup: [ { jumlah: "300 pcs", harga: "Rp. 2.800" }, { jumlah: "500 pcs", harga: "Rp. 2.300" }, { jumlah: "1000 pcs", harga: "Rp. 1.800" } ],
        estimasiPengerjaanPopup: '10-14 Hari Kerja', pengirimanDariPopup: 'Dari Kota Surakarta (Solo)',
        jasaKirimPopup: 'Pos Indonesia, JNE, J&T, atau kargo pilihan',
        notePengirimanPopup: 'Desain dapat disesuaikan dengan tema pernikahan Anda.'
    },
    {
        id: 'sv-amp-001', category: 'amplop',
        imageSrc: 'https://raw.githubusercontent.com/sakinavisuals/sakinavisuals.github.io/refs/heads/main/images/cat_lipat3/SV-LP3-001.webp', 
        altText: 'Undangan Amplop Natural', codeCard: 'KODE : SV-AMP-001',
        detailsCard: ['Kraft Liner 150gsm', 'Amplop C5', 'Simpel Elegan'],
        titlePopup: 'UNDANGAN DENGAN AMPLOP NATURAL', codePopup: 'SV-AMP-001',
        bahanPopup: 'Amplop: Kraft Liner 150 Gsm. Isi Undangan: Art Paper 210 Gsm', ukuranPopup: 'Amplop C5 (16.2 x 22.9 cm). Isi menyesuaikan.',
        bonusPopup: ['Tali Rami / Stiker Segel (Pilih salah satu)', 'Label Nama Tamu (Free Print)', 'Packing Kardus'],
        catatanTambahanPopup: 'Pilihan cetak 1 warna atau full color pada amplop tersedia (Chat Admin).',
        hargaTiersPopup: [ { jumlah: "300 pcs", harga: "Rp. 3.500" }, { jumlah: "500 pcs", harga: "Rp. 3.000" } ],
        estimasiPengerjaanPopup: '10-15 Hari Kerja', pengirimanDariPopup: 'Dari Kota Surakarta (Solo)',
        jasaKirimPopup: 'JNE, Tiki, Wahana',
        notePengirimanPopup: 'Cocok untuk tema rustic, vintage, atau natural.'
    },
    {
        id: 'sv-hc-001', category: 'hardcover', // Pastikan ID unik jika ini produk yang berbeda dari duplikat lainnya
        imageSrc: 'https://raw.githubusercontent.com/sakinavisuals/sakinavisuals.github.io/refs/heads/main/images/comson.webp', 
        altText: 'Undangan Hardcover Mewah', codeCard: 'KODE : SV-HC-001',
        detailsCard: ['Board Lapis Jasmin', '15x20cm', 'Poly Emas Mewah'],
        titlePopup: 'UNDANGAN HARDCOVER EKSKLUSIF', codePopup: 'SV-HC-001',
        bahanPopup: 'Board tebal dilapis Kertas Jasmin Import, Finishing Poly Emas pada Nama Pengantin & Inisial', 
        ukuranPopup: 'Uk. Jadi (Tertutup): 15 cm x 20 cm (Bisa request ukuran lain)',
        bonusPopup: ['Plastik OPP Tebal Pelindung', 'Label Nama Premium (Free Print Out)', 'Packing Box Individual Elegan', 'Kartu Ucapan Terima Kasih (Matching Design)'],
        catatanTambahanPopup: 'Model hardcover memberikan kesan sangat mewah dan kokoh. Bisa request warna pita, jenis kertas pelapis, atau aksesoris lain (Chat Admin untuk konsultasi).',
        hargaTiersPopup: [ { jumlah: "200 pcs", harga: "Rp. 15.000" }, { jumlah: "300 pcs", harga: "Rp. 12.500" }, { jumlah: "500 pcs", harga: "Rp. 10.000" } ],
        estimasiPengerjaanPopup: '14-21 Hari Kerja (tergantung kerumitan & antrian)',
        pengirimanDariPopup: 'Dari Kota Surakarta (Solo)',
        jasaKirimPopup: 'Direkomendasikan Kargo atau ekspedisi dengan asuransi untuk keamanan ekstra.',
        notePengirimanPopup: 'Karena kualitas premium dan proses yang detail, mohon pesan jauh-jauh hari untuk hasil maksimal.'
    }
    // Jika ada produk hardcover lain yang sama persis namun ID berbeda, pastikan ID nya unik, contoh:
    // {
    // id: 'sv-hc-002', category: 'hardcover',
    // ... (data lainnya seperti di atas)
    // },
];